### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by ml-milan-vit** [vapor-community/pagination#13]
**Question Subject**

Do you think it would be possible to add license information to the repository? Preferably in the form of a LICENSE file, similar to how all official Vapor repositories do it.

Thank you!

**Comment by anthonycastelli** [comment]
I don't have access to a computer right now, but when I get home later on next week I can get this taken care of :)

**Comment by anthonycastelli** [comment]
@ml-milan-vit Can I ask what the benefit of adding a license to this project would be? Considering most Vapor packages don't have one, is it even needed?

**Comment by ml-milan-vit** [comment]
@anthonycastelli Ah, actually all packages we use in current project have license information specified, and those who didn’t have license information clearly visible, I started annoying to publish the information 😅 Recently all Skelpo’s packages had the license information added, for example.

The benefit/importance of clearly specified license information is that when one wishes to use package in commercial project, it’s good to know beforehand if licensing troubles will come in the future. I’m probably not explaining this right at all, but let me give an example:

Imagine you started a project, and depended on a package that doesn’t have license information specified. Your project started making money, and suddenly package maintainer would decide that “hey, part of that success is mine, I want some of that profit”. I know this will surely not happen in this community, of course – but clients we’re building these projects for need more of a guarantee than “surely it won’t happen”.

I hope that clears it a little.

**Comment by anthonycastelli** [comment]
Ahh okay, I gotcha. That makes sense. Do you happen to know of any licenses that would be worth copying/using for this package? You won't have to worry about me going after you haha but I see what you mean.

**Comment by ml-milan-vit** [comment]
Hmm, Vapor uses MIT for all of its packages, so does Skelpo, LiveUI, Nodes and our company as well. I think it’s a very safe license.

**Comment by anthonycastelli** [comment]
Done. https://github.com/vapor-community/pagination/blob/master/LICENSE. Let me know if I'm forgetting anything. I just used used GitHub's License templates. I had no idea those existed haha

**Comment by ml-milan-vit** [comment]
Perfect! Thank you ❤️
