### ISSUE TITLE
Different sorting for different endpoint

### ISSUE THREAD

**Issue by andreascai** [vapor-community/pagination#18]
How to sort with different column for different endpoint in controller?

**Comment by anthonycastelli** [comment]
Overriding the `defaultPageSorts` will allow you to accomplish this on a per model basis.  https://github.com/vapor-community/pagination/blob/0cd6a77687030fd28319bda1945004994c09d430/Sources/Pagination/Paginatable.swift#L21

If you want to do it on the fly, you can add your own sorts into the paginate method. 
https://github.com/vapor-community/pagination/blob/0cd6a77687030fd28319bda1945004994c09d430/Sources/Pagination/QueryBuilder%2BPaginatable.swift#L53

**Comment by andreascai** [comment]
@anthonycastelli I want to sort with Boolean value from certain column. Could you show me some example?

**Comment by anthonycastelli** [comment]
ToIf you're gonna override at the model level, it'll be something like this
```swift
extension MyModel: Paginatable {
    static var defaultPageSorts: [MyModel.Database.QuerySort] {
        return [
            // Option #1
            MyModel.Database.querySort(MyModel.Database.queryField(.keyPath(\ MyModel.name)), MyModel Database.querySortDirectionDescending),
            // Option #2
            (\MyModel.name).querySort()
        ]
    }
}
```

If you want to do it on a route level, it'll be done something like this:
```swift
return try query.paginate(for: req, [(\Allergy.name).querySort()])
```

**Comment by andreascai** [comment]
@anthonycastelli thanks for the help. I would try that later

**Comment by anthonycastelli** [comment]
I'm gonna go ahead and close this issue, but if you do run into issues, feel free to reopen this. 🙂

**Comment by andreascai** [comment]
@anthonycastelli 
`return try query.paginate(for: req, [(\Allergy.name).querySort()])` says
Use of unresolved identifier 'query'

**Comment by andreascai** [comment]
@anthonycastelli 
`return try query.paginate(for: req, [(\Allergy.name).querySort()])` says
Use of unresolved identifier 'query'.

**Comment by andreascai** [comment]
@anthonycastelli 
```swift
return try query.paginate(for: req, [(\Allergy.name).querySort()])
``` says
Use of unresolved identifier 'query'.

**Comment by andreascai** [comment]
@anthonycastelli 
```swift
return try query.paginate(for: req, [(\Allergy.name).querySort()])
```
 says Use of unresolved identifier 'query'.
