### ISSUE TITLE
Fluent filters are missing

### ISSUE THREAD

**Issue by gperdomor** [vapor-community/pagination#2]
With the current API I can't do something like `User.query(on: req).filter(\.email == searchTerm).paginate(for: req)` in a `search`endpoint  because `paginate(for: req)` call the `all()` method.

My proposal is that `Pagination` package handle only the split and page build without querying stuff, more like an Array extension maybe 🤔 , in that way you can access to the full fluent API and do something like this:

```
func index(_ req: Request) throws -> Future<Paginated<User>> {
    return User.query(on: req).all().paginate(for: req)
}

func search(_ req: Request) throws -> Future<Paginated<User>> {
    guard let searchTerm = req.query[String.self, at: "email"] else {
        throw Abort(.badRequest)
    }
        
    return try User.query(on: req).filter(\.email == searchTerm).paginate(for: req)
}
```

**Comment by anthonycastelli** [comment]
When you do 
```swift
func index(_ req: Request) throws -> Future<Paginated<User>> {
    return User.query(on: req).paginate(for: req)
}
```
The results should be returned paginated. You don't need to append the `.all()` before paginating.

**Comment by gperdomor** [comment]
Yeah, that's fine... the problem is when I need filter things... Like this...
```
return try User.query(on: req).filter(\.name == searchTerm).paginate(for: req)
```

I need some users with some names, I can't paginate that results

**Comment by anthonycastelli** [comment]
I'll have to look into this again, but last I had checked, I was just fetching the request from the query already built. https://github.com/vapor-community/pagination/blob/master/Sources/Pagination/QueryBuilder%2BPaginatable.swift#L13. Does it just fetch all of the results regardless of the search term?

**Comment by anthonycastelli** [comment]
Ahh, I see whats going on here. Let me work out a fix.

**Comment by gperdomor** [comment]
In my case always get all the users...

My code:
```
func search(_ req: Request) throws -> Future<Paginated<User>> {
        guard let searchTerm = req.query[String.self, at: "email"] else {
            throw Abort(.badRequest)
        }
        
        return try User.query(on: req).filter(\.email == searchTerm).paginate(for: req)
}
```

The results

<img width="1440" alt="screen shot 2018-04-30 at 5 43 16 pm" src="https://user-images.githubusercontent.com/371939/39449316-17f07ee0-4c9e-11e8-94d8-d05a15d18946.png">

**Comment by gperdomor** [comment]
I think the problem is the line 40 when you call `all()`

**Comment by anthonycastelli** [comment]
The issue is from here https://github.com/vapor-community/pagination/blob/677b712da51d230a1b3c5a5971a470803274dc43/Sources/Pagination/Model%2BPaginatable.swift#L16-L20. Whats happening is the Model (`Self`) is reconstructing its own query. Let me work out a fix. 🙂

**Comment by gperdomor** [comment]
I can't convert my users to a PublicUser struct (to exclude password field in the response) without conform Model in the PublicUser, maybe I'm not doing in the correct way... Can you validate that please?

**Comment by anthonycastelli** [comment]
Regarding your issue for converting to a struct, currently, there is no "smart" way to handle that. Once Fluent is tagged and Tanner has finned releasing Vapor 3, I'm gonna bug him with some ideas on how to approach this one.

**Comment by gperdomor** [comment]
@anthonycastelli any progress with your last comment?
