### ISSUE TITLE
Public vars?

### ISSUE THREAD

**Issue by khoogheem** [vapor-community/pagination#8]
any reason not to make the vars public?
```
public struct Position: Content {
    var current: Int
    var next: Int?
    var previous: Int?
    var max: Int
}
public struct PageData: Content {
    var per: Int
    var total: Int
}
public struct PageInfo: Content {
    var position: Position
    var data: PageData
}
public struct Paginated<M: Content>: Content {
    var page: PageInfo
    var data: [M]
}
```

**Comment by anthonycastelli** [comment]
I just double checked, and with the latest release, which is `1.0.2`, they are public. 

https://github.com/vapor-community/pagination/blob/a9edc1737ec8f2508b4748cf8f8e9276314c4cb7/Sources/Pagination/Paginated.swift#L12-L54

**Comment by khoogheem** [comment]
```
        return try Product.makePaginate(req).flatMap(to: View.self) { products in
           let max =  products.page.position.max
```
produces: 'page' is inaccessible due to 'internal' protection level

The vars default to internal if nothing is there..

**Comment by anthonycastelli** [comment]
Oh I see, the actual variables inside of the structs themselves. I'll fix that up and push an update for it. 👍

**Comment by anthonycastelli** [comment]
Go ahead and update to 1.0.3
https://github.com/vapor-community/pagination/releases/tag/1.0.3
